### ISSUE TITLE
Post sample code for raspberry pi

### ISSUE THREAD

**Issue by raducojocari** [DFRobot/Analog-AC-Current-Sensor#1]
Although this repo seems to be specific around arduino code, is it possible to post an example for using the AC sensor with a raspberry pi?

For reading data from an ADC this library seems to work quite well: https://github.com/ncd-io/ncd-red-ads1115

I am interested in understanding how you would convert the data that comes from the ADC into AC current value.

**Comment by qsjhyy** [comment]
Since there is no built-in ADC on the Raspberry PI, we need an external ADC chip when we need to read analog data with the raspberry PI, so we will not add a raspberry PI use example. However, if you have the raspberry PI on your own, you can modify it directly from the Aduino library.
